apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: msa-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            - name: data
              mountPath: /data
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: data
          emptyDir: {}
