apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: msa-apps
  labels:
    app: minio
spec:
  ports:
    - port: 9100
      name: api
      targetPort: 9100
    - port: 9101
      name: console
      targetPort: 9101
  selector:
    app: minio
