apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: msa-apps
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: MYSQL_DATABASE
              value: "health_db"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          command:
            - "bash"
            - "-c"
            - "mysqld --default-authentication-plugin=mysql_native_password & sleep 10 && mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'CREATE DATABASE IF NOT EXISTS user_db; GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"%\";' && wait"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc