apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: msa-apps
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: http
  selector:
    app: rabbitmq
---
# 관리 UI 접근을 위한 NodePort 서비스
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: msa-apps
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 31672
      name: http
  selector:
    app: rabbitmq
