server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ********
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ********
    password: ********
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
  data:
    redis:
      host: localhost
      port: 6379
      password: ********

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
