server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ********
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
  minio:
    endpoint: http://localhost:9100
    external-endpoint: http://localhost:9100
    accessKey: ********
    secretKey: ********
    bucket:
      name: health-images
      location: local

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
