spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ********
    password: ********
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
